"""empty message

Revision ID: c51c359e3598
Revises: 5c969c45bb53
Create Date: 2017-09-18 21:39:59.104226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c51c359e3598'
down_revision = '5c969c45bb53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'feature', ['id'])
    op.create_unique_constraint(None, 'scenario', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scenario', type_='unique')
    op.drop_constraint(None, 'feature', type_='unique')
    # ### end Alembic commands ###
